### ISSUE TITLE
Did you faced any Issue with igpu ?

### ISSUE THREAD

**Issue by ssoad** [MAGICXcmd/Ryzentosh#2]

**Comment by MAGICXcmd** [comment]
I've been testing NootedRed with iGPU for a week now. The problems I have encountered are artifacts in browsers running on the Chromium engine, an Apple TV that is not working. 

There were no problems during installation.

If you need a specific application, I am ready to check and tell you whether it works or not.

**Comment by pepexd0001** [comment]
It worked for me **EFI**, thank you very much, I have the same processor with an **Asus B450M A-II** motherboard, I don't have a **GPU** at the moment and that's why I wanted to test, I'm aware that it will have bugs; however, if it doesn't affect the performance I'll be relaxed.

**Comment by ssoad** [comment]
But It's not worked for me I've Gigabyte B550M DS3H with 5600G. System
can't start.

**Comment by MAGICXcmd** [comment]
@ssoad 
You may have configured the BIOS incorrectly.
I wrote more about my bios settings in [README.md #BIOS](https://github.com/MAGICXcmd/Ryzentosh#-bios)
